/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2020-10-6:  2h:23m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tysum_3 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_4 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_5 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_6 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
atstype_boxed atslab__2 ;
} postiats_tysum_7 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
atstype_boxed atslab__2 ;
} postiats_tysum_8 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm, (atstype_boxed), atsvoid_t0ype) ;
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp, (atstype_boxed), atstype_boxed) ;
ATSdyncst_mac(atspre_print_int)
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_change, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatmpdec(statmp0, atstype_boxed) ;
ATSstatmpdec(statmp1, atstype_boxed) ;
ATSstatmpdec(statmp2, atstype_boxed) ;
ATSstatmpdec(statmp3, atstype_boxed) ;
ATSstatmpdec(statmp4, atstype_boxed) ;
ATSstatmpdec(statmp5, atstype_boxed) ;
ATSstatmpdec(statmp6, atstype_boxed) ;
ATSstatmpdec(statmp7, atstype_boxed) ;
ATSstatmpdec(statmp8, atstype_boxed) ;
ATSstatmpdec(statmp9, atstype_boxed) ;
ATSstatmpdec(statmp10, atstype_boxed) ;
ATSstatmpdec(statmp11, atstype_boxed) ;
ATSstatmpdec(statmp12, atstype_boxed) ;
ATSstatmpdec(statmp13, atstype_boxed) ;
ATSstatmpdec(statmp14, atstype_boxed) ;
ATSstatmpdec(statmp15, atstype_boxed) ;
ATSstatmpdec(statmp16, atstype_boxed) ;
ATSstatmpdec(statmp17, atstype_boxed) ;
ATSstatmpdec(statmp18, atstype_boxed) ;
ATSstatmpdec(statmp19, atstype_boxed) ;
ATSstatmpdec(statmp20, atstype_boxed) ;
ATSstatmpdec(statmp21, atstype_boxed) ;
ATSstatmpdec(statmp22, atstype_boxed) ;
ATSstatmpdec(statmp23, atstype_boxed) ;
ATSstatmpdec(statmp24, atstype_boxed) ;
ATSstatmpdec(statmp25, atstype_boxed) ;
ATSstatmpdec(statmp26, atstype_boxed) ;
ATSstatmpdec(statmp27, atstype_boxed) ;
ATSstatmpdec(statmp28, atstype_boxed) ;
ATSstatmpdec(statmp29, atstype_boxed) ;
ATSstatmpdec(statmp30, atstype_boxed) ;
ATSstatmpdec(statmp31, atstype_boxed) ;
ATSstatmpdec(statmp32, atstype_boxed) ;
ATSstatmpdec(statmp33, atstype_boxed) ;
ATSstatmpdec(statmp34, atstype_boxed) ;
ATSstatmpdec(statmp35, atstype_boxed) ;
ATSstatmpdec(statmp36, atstype_boxed) ;
ATSstatmpdec(statmp37, atstype_boxed) ;
ATSstatmpdec(statmp38, atstype_boxed) ;
ATSstatmpdec(statmp39, atstype_boxed) ;
ATSstatmpdec(statmp40, atstype_boxed) ;
ATSstatmpdec(statmp41, atstype_boxed) ;
ATSstatmpdec(statmp42, atstype_boxed) ;
ATSstatmpdec(statmp43, atstype_boxed) ;
ATSstatmpdec(statmp44, atstype_boxed) ;
ATSstatmpdec(statmp45, atstype_boxed) ;
ATSstatmpdec(statmp46, atstype_boxed) ;
ATSstatmpdec(statmp47, atstype_boxed) ;
ATSstatmpdec(statmp48, atstype_boxed) ;
ATSstatmpdec(statmp49, atstype_boxed) ;
ATSstatmpdec(statmp50, atstype_boxed) ;
ATSstatmpdec(statmp51, atstype_boxed) ;
ATSstatmpdec(statmp52, atstype_boxed) ;
ATSstatmpdec(statmp53, atstype_boxed) ;
ATSstatmpdec(statmp54, atstype_boxed) ;
ATSstatmpdec(statmp55, atstype_boxed) ;
ATSstatmpdec(statmp56, atstype_boxed) ;
ATSstatmpdec(statmp57, atstype_boxed) ;
ATSstatmpdec(statmp58, atstype_boxed) ;
ATSstatmpdec(statmp59, atstype_boxed) ;
ATSstatmpdec(statmp60, atstype_boxed) ;
ATSstatmpdec(statmp61, atstype_boxed) ;
ATSstatmpdec(statmp62, atstype_boxed) ;
ATSstatmpdec(statmp63, atstype_boxed) ;
ATSstatmpdec(statmp64, atstype_boxed) ;
ATSstatmpdec(statmp65, atstype_boxed) ;
ATSstatmpdec(statmp66, atstype_boxed) ;
ATSstatmpdec(statmp67, atstype_boxed) ;
ATSstatmpdec(statmp68, atstype_boxed) ;
ATSstatmpdec(statmp69, atstype_boxed) ;
ATSstatmpdec(statmp70, atstype_boxed) ;
ATSstatmpdec(statmp71, atstype_boxed) ;
ATSstatmpdec(statmp72, atstype_boxed) ;
ATSstatmpdec(statmp73, atstype_boxed) ;
ATSstatmpdec(statmp74, atstype_boxed) ;
ATSstatmpdec(statmp75, atstype_boxed) ;
ATSstatmpdec(statmp76, atstype_boxed) ;
ATSstatmpdec(statmp77, atstype_boxed) ;
ATSstatmpdec(statmp78, atstype_boxed) ;
ATSstatmpdec(statmp79, atstype_boxed) ;
#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2012(line=97, offs=6) -- 3184(line=123, offs=2)
*/
/*
local: 
global: mainats_0_void$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret80) ;
// ATStmpdec_void(tmp81) ;
// ATStmpdec_void(tmp82) ;
// ATStmpdec_void(tmp83) ;
// ATStmpdec_void(tmp84) ;
// ATStmpdec_void(tmp85) ;
// ATStmpdec_void(tmp86) ;
// ATStmpdec_void(tmp87) ;
// ATStmpdec_void(tmp88) ;
// ATStmpdec_void(tmp89) ;
// ATStmpdec_void(tmp90) ;
// ATStmpdec_void(tmp91) ;
// ATStmpdec_void(tmp92) ;
// ATStmpdec_void(tmp93) ;
// ATStmpdec_void(tmp94) ;
// ATStmpdec_void(tmp95) ;
// ATStmpdec_void(tmp96) ;
// ATStmpdec_void(tmp97) ;
// ATStmpdec_void(tmp98) ;
ATStmpdec(tmp99, atstype_boxed) ;
// ATStmpdec_void(tmp100) ;
// ATStmpdec_void(tmp101) ;
// ATStmpdec_void(tmp102) ;
// ATStmpdec_void(tmp103) ;
// ATStmpdec_void(tmp104) ;
// ATStmpdec_void(tmp105) ;
// ATStmpdec_void(tmp106) ;
ATStmpdec(tmp107, atstype_boxed) ;
// ATStmpdec_void(tmp108) ;
// ATStmpdec_void(tmp109) ;
// ATStmpdec_void(tmp110) ;
// ATStmpdec_void(tmp111) ;
// ATStmpdec_void(tmp112) ;
ATStmpdec(tmp113, atstype_boxed) ;
// ATStmpdec_void(tmp114) ;
// ATStmpdec_void(tmp115) ;
ATStmpdec(tmp116, atstype_boxed) ;
ATStmpdec(tmp117, atstype_boxed) ;
// ATStmpdec_void(tmp118) ;
// ATStmpdec_void(tmp119) ;
// ATStmpdec_void(tmp120) ;
// ATStmpdec_void(tmp121) ;
// ATStmpdec_void(tmp122) ;
// ATStmpdec_void(tmp123) ;
// ATStmpdec_void(tmp124) ;
// ATStmpdec_void(tmp125) ;
// ATStmpdec_void(tmp126) ;
// ATStmpdec_void(tmp127) ;
ATStmpdec(tmp128, atstype_boxed) ;
ATStmpdec(tmp129, atstype_boxed) ;
ATStmpdec(tmp130, atstype_boxed) ;
ATStmpdec(tmp131, atstype_boxed) ;
// ATStmpdec_void(tmp132) ;
// ATStmpdec_void(tmp133) ;
// ATStmpdec_void(tmp134) ;
// ATStmpdec_void(tmp135) ;
// ATStmpdec_void(tmp136) ;
// ATStmpdec_void(tmp137) ;
// ATStmpdec_void(tmp138) ;
ATStmpdec(tmp139, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp140) ;
// ATStmpdec_void(tmp141) ;
// ATStmpdec_void(tmp142) ;
// ATStmpdec_void(tmp143) ;
// ATStmpdec_void(tmp144) ;
ATStmpdec(tmp145, atstype_boxed) ;
ATStmpdec(tmp146, atstype_boxed) ;
ATStmpdec(tmp147, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2007(line=97, offs=1) -- 3184(line=123, offs=2)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2017(line=98, offs=1) -- 3184(line=123, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2025(line=99, offs=7) -- 2079(line=99, offs=61)
*/
ATSINSmove_void(tmp81, atspre_print_string(ATSPMVstring("*** Q1: Implementing T0Mtup and T0mPrj ***"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2025(line=99, offs=7) -- 2079(line=99, offs=61)
*/
ATSINSmove_void(tmp82, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2086(line=100, offs=7) -- 2125(line=100, offs=46)
*/
ATSINSmove_void(tmp83, atspre_print_string(ATSPMVstring("\nTesting print for T0Mtup:"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2086(line=100, offs=7) -- 2125(line=100, offs=46)
*/
ATSINSmove_void(tmp84, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2132(line=101, offs=7) -- 2157(line=101, offs=32)
*/
ATSINSmove_void(tmp85, atspre_print_string(ATSPMVstring("tup0 = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2132(line=101, offs=7) -- 2157(line=101, offs=32)
*/
ATSINSmove_void(tmp86, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(statmp5)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2132(line=101, offs=7) -- 2157(line=101, offs=32)
*/
ATSINSmove_void(tmp87, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2165(line=103, offs=7) -- 2204(line=103, offs=46)
*/
ATSINSmove_void(tmp88, atspre_print_string(ATSPMVstring("\nTesting print for T0Mprj:"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2165(line=103, offs=7) -- 2204(line=103, offs=46)
*/
ATSINSmove_void(tmp89, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2211(line=104, offs=7) -- 2236(line=104, offs=32)
*/
ATSINSmove_void(tmp90, atspre_print_string(ATSPMVstring("tpr0 = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2211(line=104, offs=7) -- 2236(line=104, offs=32)
*/
ATSINSmove_void(tmp91, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(statmp6)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2211(line=104, offs=7) -- 2236(line=104, offs=32)
*/
ATSINSmove_void(tmp92, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2244(line=106, offs=7) -- 2302(line=106, offs=65)
*/
ATSINSmove_void(tmp93, atspre_print_string(ATSPMVstring("\nTesting interp(T0Mprj) without substitution:"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2244(line=106, offs=7) -- 2302(line=106, offs=65)
*/
ATSINSmove_void(tmp94, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2309(line=107, offs=7) -- 2362(line=107, offs=60)
*/
ATSINSmove_void(tmp95, atspre_print_string(ATSPMVstring("interp("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2309(line=107, offs=7) -- 2362(line=107, offs=60)
*/
ATSINSmove_void(tmp96, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(statmp6)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2309(line=107, offs=7) -- 2362(line=107, offs=60)
*/
ATSINSmove_void(tmp97, atspre_print_string(ATSPMVstring(") = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2343(line=107, offs=41) -- 2360(line=107, offs=58)
*/
ATSINSmove(tmp99, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp(statmp6)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2309(line=107, offs=7) -- 2362(line=107, offs=60)
*/
ATSINSmove_void(tmp98, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp99)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2309(line=107, offs=7) -- 2362(line=107, offs=60)
*/
ATSINSmove_void(tmp100, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2370(line=109, offs=7) -- 2425(line=109, offs=62)
*/
ATSINSmove_void(tmp101, atspre_print_string(ATSPMVstring("\nTesting interp(T0Mtup) with substitution:"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2370(line=109, offs=7) -- 2425(line=109, offs=62)
*/
ATSINSmove_void(tmp102, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2432(line=110, offs=7) -- 2485(line=110, offs=60)
*/
ATSINSmove_void(tmp103, atspre_print_string(ATSPMVstring("interp("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2432(line=110, offs=7) -- 2485(line=110, offs=60)
*/
ATSINSmove_void(tmp104, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(statmp7)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2432(line=110, offs=7) -- 2485(line=110, offs=60)
*/
ATSINSmove_void(tmp105, atspre_print_string(ATSPMVstring(") = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2466(line=110, offs=41) -- 2483(line=110, offs=58)
*/
ATSINSmove(tmp107, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp(statmp7)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2432(line=110, offs=7) -- 2485(line=110, offs=60)
*/
ATSINSmove_void(tmp106, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp107)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2432(line=110, offs=7) -- 2485(line=110, offs=60)
*/
ATSINSmove_void(tmp108, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2493(line=112, offs=7) -- 2548(line=112, offs=62)
*/
ATSINSmove_void(tmp109, atspre_print_string(ATSPMVstring("\nTesting interp(T0Mprj) with substitution:"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2493(line=112, offs=7) -- 2548(line=112, offs=62)
*/
ATSINSmove_void(tmp110, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2555(line=113, offs=7) -- 2629(line=113, offs=81)
*/
ATSINSmove_void(tmp111, atspre_print_string(ATSPMVstring("interp("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2575(line=113, offs=27) -- 2589(line=113, offs=41)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp113, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(tmp113, 6) ;
// #endif
ATSINSstore_con1_ofs(tmp113, postiats_tysum_3, atslab__0, statmp7) ;
ATSINSstore_con1_ofs(tmp113, postiats_tysum_3, atslab__1, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2555(line=113, offs=7) -- 2629(line=113, offs=81)
*/
ATSINSmove_void(tmp112, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp113)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2555(line=113, offs=7) -- 2629(line=113, offs=81)
*/
ATSINSmove_void(tmp114, atspre_print_string(ATSPMVstring(") = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2613(line=113, offs=65) -- 2627(line=113, offs=79)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp117, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(tmp117, 6) ;
// #endif
ATSINSstore_con1_ofs(tmp117, postiats_tysum_3, atslab__0, statmp7) ;
ATSINSstore_con1_ofs(tmp117, postiats_tysum_3, atslab__1, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2600(line=113, offs=52) -- 2628(line=113, offs=80)
*/
ATSINSmove(tmp116, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp(tmp117)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2555(line=113, offs=7) -- 2629(line=113, offs=81)
*/
ATSINSmove_void(tmp115, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp116)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2555(line=113, offs=7) -- 2629(line=113, offs=81)
*/
ATSINSmove_void(tmp118, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2637(line=115, offs=7) -- 2700(line=115, offs=70)
*/
ATSINSmove_void(tmp119, atspre_print_string(ATSPMVstring("\n\n*** Q2: Implementing coin_change by lambda0 ***"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2637(line=115, offs=7) -- 2700(line=115, offs=70)
*/
ATSINSmove_void(tmp120, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2707(line=116, offs=7) -- 2739(line=116, offs=39)
*/
ATSINSmove_void(tmp121, atspre_print_string(ATSPMVstring("\nThe coins = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2707(line=116, offs=7) -- 2739(line=116, offs=39)
*/
ATSINSmove_void(tmp122, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(statmp19)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2707(line=116, offs=7) -- 2739(line=116, offs=39)
*/
ATSINSmove_void(tmp123, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2746(line=117, offs=7) -- 2800(line=117, offs=61)
*/
ATSINSmove_void(tmp124, atspre_print_string(ATSPMVstring("\nTesting lambda based coin_get function :"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2746(line=117, offs=7) -- 2800(line=117, offs=61)
*/
ATSINSmove_void(tmp125, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2807(line=118, offs=7) -- 2894(line=118, offs=94)
*/
ATSINSmove_void(tmp126, atspre_print_string(ATSPMVstring("coin_get(list,1) = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2859(line=118, offs=59) -- 2881(line=118, offs=81)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp130, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(tmp130, 4) ;
// #endif
ATSINSstore_con1_ofs(tmp130, postiats_tysum_5, atslab__0, statmp23) ;
ATSINSstore_con1_ofs(tmp130, postiats_tysum_5, atslab__1, statmp19) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2882(line=118, offs=82) -- 2891(line=118, offs=91)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp131, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(tmp131, 0) ;
// #endif
ATSINSstore_con1_ofs(tmp131, postiats_tysum_6, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2852(line=118, offs=52) -- 2892(line=118, offs=92)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp129, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(tmp129, 4) ;
// #endif
ATSINSstore_con1_ofs(tmp129, postiats_tysum_5, atslab__0, tmp130) ;
ATSINSstore_con1_ofs(tmp129, postiats_tysum_5, atslab__1, tmp131) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2839(line=118, offs=39) -- 2893(line=118, offs=93)
*/
ATSINSmove(tmp128, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp(tmp129)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2807(line=118, offs=7) -- 2894(line=118, offs=94)
*/
ATSINSmove_void(tmp127, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp128)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2807(line=118, offs=7) -- 2894(line=118, offs=94)
*/
ATSINSmove_void(tmp132, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2901(line=119, offs=7) -- 2945(line=119, offs=51)
*/
ATSINSmove_void(tmp133, atspre_print_string(ATSPMVstring("\nTesting coin_change function: "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2901(line=119, offs=7) -- 2945(line=119, offs=51)
*/
ATSINSmove_void(tmp134, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2952(line=120, offs=7) -- 3047(line=120, offs=102)
*/
ATSINSmove_void(tmp135, atspre_print_string(ATSPMVstring("The result from coin_change("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2952(line=120, offs=7) -- 3047(line=120, offs=102)
*/
ATSINSmove_void(tmp136, atspre_print_int(ATSPMVi0nt(300))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2952(line=120, offs=7) -- 3047(line=120, offs=102)
*/
ATSINSmove_void(tmp137, atspre_print_string(ATSPMVstring(") which is impelemented by ATS = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3031(line=120, offs=86) -- 3045(line=120, offs=100)
*/
ATSINSmove(tmp139, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_change(ATSPMVi0nt(300))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2952(line=120, offs=7) -- 3047(line=120, offs=102)
*/
ATSINSmove_void(tmp138, atspre_print_int(tmp139)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2952(line=120, offs=7) -- 3047(line=120, offs=102)
*/
ATSINSmove_void(tmp140, atspre_print_newline()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3054(line=121, offs=7) -- 3181(line=121, offs=134)
*/
ATSINSmove_void(tmp141, atspre_print_string(ATSPMVstring("The result from coin_change("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3054(line=121, offs=7) -- 3181(line=121, offs=134)
*/
ATSINSmove_void(tmp142, atspre_print_int(ATSPMVi0nt(300))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3054(line=121, offs=7) -- 3181(line=121, offs=134)
*/
ATSINSmove_void(tmp143, atspre_print_string(ATSPMVstring(") which is impelemented by lambda0 = "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3169(line=121, offs=122) -- 3177(line=121, offs=130)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp147, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(tmp147, 0) ;
// #endif
ATSINSstore_con1_ofs(tmp147, postiats_tysum_6, atslab__0, ATSPMVi0nt(300)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3150(line=121, offs=103) -- 3179(line=121, offs=132)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp146, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(tmp146, 4) ;
// #endif
ATSINSstore_con1_ofs(tmp146, postiats_tysum_5, atslab__0, statmp75) ;
ATSINSstore_con1_ofs(tmp146, postiats_tysum_5, atslab__1, tmp147) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3137(line=121, offs=90) -- 3180(line=121, offs=133)
*/
ATSINSmove(tmp145, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__t0erm_interp(tmp146)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3054(line=121, offs=7) -- 3181(line=121, offs=134)
*/
ATSINSmove_void(tmp144, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(tmp145)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 3054(line=121, offs=7) -- 3181(line=121, offs=134)
*/
ATSINSmove_void(tmpret80, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 2017(line=98, offs=1) -- 3184(line=123, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret80) ;
} /* end of [mainats_0_void] */

ATSdynloadflag_init(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynload(/*void*/) ;
ATSdynloadflag_init(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_interp_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_interp_056_dats__dynload(/*void*/) ;
ATSdynloadflag_init(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynload(/*void*/) ;
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
ATSdynloadfcall(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynload) ;
ATSdynloadfcall(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_interp_056_dats__dynload) ;
ATSdynloadfcall(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynload) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 458(line=23, offs=8) -- 477(line=23, offs=27)
*/

ATSINSmove_nil(statmp0) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 504(line=24, offs=27) -- 516(line=24, offs=39)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp2, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp2, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp2, postiats_tysum_0, atslab__0, ATSPMVstring("x0")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 485(line=24, offs=8) -- 520(line=24, offs=43)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp1, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp1, 1) ;
#endif
ATSINSstore_con1_ofs(statmp1, postiats_tysum_1, atslab__0, statmp2) ;
ATSINSstore_con1_ofs(statmp1, postiats_tysum_1, atslab__1, statmp0) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 547(line=25, offs=27) -- 559(line=25, offs=39)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp4, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp4, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp4, postiats_tysum_0, atslab__0, ATSPMVstring("x1")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 528(line=25, offs=8) -- 563(line=25, offs=43)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp3, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp3, 1) ;
#endif
ATSINSstore_con1_ofs(statmp3, postiats_tysum_1, atslab__0, statmp4) ;
ATSINSstore_con1_ofs(statmp3, postiats_tysum_1, atslab__1, statmp1) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 573(line=26, offs=10) -- 582(line=26, offs=19)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp5, postiats_tysum_2) ;
// #if(1)
ATSINSstore_con1_tag(statmp5, 5) ;
// #endif
ATSINSstore_con1_ofs(statmp5, postiats_tysum_2, atslab__0, statmp3) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 593(line=27, offs=10) -- 607(line=27, offs=24)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp6, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(statmp6, 6) ;
// #endif
ATSINSstore_con1_ofs(statmp6, postiats_tysum_3, atslab__0, statmp5) ;
ATSINSstore_con1_ofs(statmp6, postiats_tysum_3, atslab__1, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 624(line=28, offs=17) -- 641(line=28, offs=34)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp8, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp8, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp8, postiats_tysum_4, atslab__0, ATSPMVstring("x0")) ;
ATSINSstore_con1_ofs(statmp8, postiats_tysum_4, atslab__1, statmp5) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 642(line=28, offs=35) -- 653(line=28, offs=46)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp9, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp9, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp9, postiats_tysum_0, atslab__0, ATSPMVstring("y")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 617(line=28, offs=10) -- 654(line=28, offs=47)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp7, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp7, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp7, postiats_tysum_5, atslab__0, statmp8) ;
ATSINSstore_con1_ofs(statmp7, postiats_tysum_5, atslab__1, statmp9) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 717(line=32, offs=29) -- 727(line=32, offs=39)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp11, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp11, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp11, postiats_tysum_6, atslab__0, ATSPMVi0nt(25)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 728(line=32, offs=40) -- 740(line=32, offs=52)
*/

ATSINSmove_nil(statmp12) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 698(line=32, offs=10) -- 741(line=32, offs=53)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp10, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp10, 1) ;
#endif
ATSINSstore_con1_ofs(statmp10, postiats_tysum_1, atslab__0, statmp11) ;
ATSINSstore_con1_ofs(statmp10, postiats_tysum_1, atslab__1, statmp12) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 770(line=33, offs=29) -- 780(line=33, offs=39)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp14, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp14, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp14, postiats_tysum_6, atslab__0, ATSPMVi0nt(10)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 751(line=33, offs=10) -- 786(line=33, offs=45)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp13, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp13, 1) ;
#endif
ATSINSstore_con1_ofs(statmp13, postiats_tysum_1, atslab__0, statmp14) ;
ATSINSstore_con1_ofs(statmp13, postiats_tysum_1, atslab__1, statmp10) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 815(line=34, offs=29) -- 824(line=34, offs=38)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp16, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp16, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp16, postiats_tysum_6, atslab__0, ATSPMVi0nt(5)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 796(line=34, offs=10) -- 830(line=34, offs=44)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp15, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp15, 1) ;
#endif
ATSINSstore_con1_ofs(statmp15, postiats_tysum_1, atslab__0, statmp16) ;
ATSINSstore_con1_ofs(statmp15, postiats_tysum_1, atslab__1, statmp13) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 859(line=35, offs=29) -- 868(line=35, offs=38)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp18, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp18, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp18, postiats_tysum_6, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 840(line=35, offs=10) -- 874(line=35, offs=44)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp17, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(statmp17, 1) ;
#endif
ATSINSstore_con1_ofs(statmp17, postiats_tysum_1, atslab__0, statmp18) ;
ATSINSstore_con1_ofs(statmp17, postiats_tysum_1, atslab__1, statmp15) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 885(line=36, offs=11) -- 896(line=36, offs=22)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp19, postiats_tysum_2) ;
// #if(1)
ATSINSstore_con1_tag(statmp19, 5) ;
// #endif
ATSINSstore_con1_ofs(statmp19, postiats_tysum_2, atslab__0, statmp17) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 907(line=37, offs=10) -- 920(line=37, offs=23)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp20, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp20, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp20, postiats_tysum_0, atslab__0, ATSPMVstring("sum")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 928(line=38, offs=8) -- 939(line=38, offs=19)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp21, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp21, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp21, postiats_tysum_0, atslab__0, ATSPMVstring("n")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 948(line=39, offs=9) -- 961(line=39, offs=22)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp22, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp22, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp22, postiats_tysum_0, atslab__0, ATSPMVstring("aux")) ;
ATSINSmove_con1_end()
/* (*nothing*) */
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1083(line=46, offs=22) -- 1094(line=46, offs=33)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp27, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp27, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp27, postiats_tysum_0, atslab__0, ATSPMVstring("n")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1095(line=46, offs=34) -- 1104(line=46, offs=43)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp28, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp28, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp28, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1071(line=46, offs=10) -- 1105(line=46, offs=44)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp26, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp26, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp26, postiats_tysum_7, atslab__0, ATSPMVstring("=")) ;
ATSINSstore_con1_ofs(statmp26, postiats_tysum_7, atslab__1, statmp27) ;
ATSINSstore_con1_ofs(statmp26, postiats_tysum_7, atslab__2, statmp28) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1116(line=47, offs=10) -- 1129(line=47, offs=23)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp30, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp30, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp30, postiats_tysum_0, atslab__0, ATSPMVstring("tup")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1109(line=47, offs=3) -- 1132(line=47, offs=26)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp29, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(statmp29, 6) ;
// #endif
ATSINSstore_con1_ofs(statmp29, postiats_tysum_3, atslab__0, statmp30) ;
ATSINSstore_con1_ofs(statmp29, postiats_tysum_3, atslab__1, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1156(line=48, offs=24) -- 1167(line=48, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp33, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp33, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp33, postiats_tysum_0, atslab__0, ATSPMVstring("n")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1168(line=48, offs=36) -- 1177(line=48, offs=45)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp34, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp34, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp34, postiats_tysum_6, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1144(line=48, offs=12) -- 1178(line=48, offs=46)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp32, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp32, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp32, postiats_tysum_7, atslab__0, ATSPMVstring("=")) ;
ATSINSstore_con1_ofs(statmp32, postiats_tysum_7, atslab__1, statmp33) ;
ATSINSstore_con1_ofs(statmp32, postiats_tysum_7, atslab__2, statmp34) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1189(line=49, offs=10) -- 1202(line=49, offs=23)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp36, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp36, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp36, postiats_tysum_0, atslab__0, ATSPMVstring("tup")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1182(line=49, offs=3) -- 1205(line=49, offs=26)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp35, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(statmp35, 6) ;
// #endif
ATSINSstore_con1_ofs(statmp35, postiats_tysum_3, atslab__0, statmp36) ;
ATSINSstore_con1_ofs(statmp35, postiats_tysum_3, atslab__1, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1229(line=50, offs=24) -- 1240(line=50, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp39, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp39, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp39, postiats_tysum_0, atslab__0, ATSPMVstring("n")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1241(line=50, offs=36) -- 1250(line=50, offs=45)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp40, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp40, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp40, postiats_tysum_6, atslab__0, ATSPMVi0nt(2)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1217(line=50, offs=12) -- 1251(line=50, offs=46)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp38, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp38, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp38, postiats_tysum_7, atslab__0, ATSPMVstring("=")) ;
ATSINSstore_con1_ofs(statmp38, postiats_tysum_7, atslab__1, statmp39) ;
ATSINSstore_con1_ofs(statmp38, postiats_tysum_7, atslab__2, statmp40) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1262(line=51, offs=10) -- 1275(line=51, offs=23)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp42, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp42, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp42, postiats_tysum_0, atslab__0, ATSPMVstring("tup")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1255(line=51, offs=3) -- 1278(line=51, offs=26)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp41, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(statmp41, 6) ;
// #endif
ATSINSstore_con1_ofs(statmp41, postiats_tysum_3, atslab__0, statmp42) ;
ATSINSstore_con1_ofs(statmp41, postiats_tysum_3, atslab__1, ATSPMVi0nt(2)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1302(line=52, offs=24) -- 1313(line=52, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp45, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp45, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp45, postiats_tysum_0, atslab__0, ATSPMVstring("n")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1314(line=52, offs=36) -- 1323(line=52, offs=45)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp46, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp46, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp46, postiats_tysum_6, atslab__0, ATSPMVi0nt(3)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1290(line=52, offs=12) -- 1324(line=52, offs=46)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp44, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp44, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp44, postiats_tysum_7, atslab__0, ATSPMVstring("=")) ;
ATSINSstore_con1_ofs(statmp44, postiats_tysum_7, atslab__1, statmp45) ;
ATSINSstore_con1_ofs(statmp44, postiats_tysum_7, atslab__2, statmp46) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1335(line=53, offs=10) -- 1348(line=53, offs=23)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp48, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp48, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp48, postiats_tysum_0, atslab__0, ATSPMVstring("tup")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1328(line=53, offs=3) -- 1351(line=53, offs=26)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp47, postiats_tysum_3) ;
// #if(1)
ATSINSstore_con1_tag(statmp47, 6) ;
// #endif
ATSINSstore_con1_ofs(statmp47, postiats_tysum_3, atslab__0, statmp48) ;
ATSINSstore_con1_ofs(statmp47, postiats_tysum_3, atslab__1, ATSPMVi0nt(3)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1357(line=55, offs=3) -- 1366(line=55, offs=12)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp49, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp49, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp49, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1282(line=52, offs=4) -- 1369(line=56, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp43, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp43, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp43, postiats_tysum_8, atslab__0, statmp44) ;
ATSINSstore_con1_ofs(statmp43, postiats_tysum_8, atslab__1, statmp47) ;
ATSINSstore_con1_ofs(statmp43, postiats_tysum_8, atslab__2, statmp49) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1209(line=50, offs=4) -- 1372(line=57, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp37, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp37, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp37, postiats_tysum_8, atslab__0, statmp38) ;
ATSINSstore_con1_ofs(statmp37, postiats_tysum_8, atslab__1, statmp41) ;
ATSINSstore_con1_ofs(statmp37, postiats_tysum_8, atslab__2, statmp43) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1136(line=48, offs=4) -- 1375(line=58, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp31, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp31, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp31, postiats_tysum_8, atslab__0, statmp32) ;
ATSINSstore_con1_ofs(statmp31, postiats_tysum_8, atslab__1, statmp35) ;
ATSINSstore_con1_ofs(statmp31, postiats_tysum_8, atslab__2, statmp37) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1063(line=46, offs=2) -- 1378(line=59, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp25, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp25, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp25, postiats_tysum_8, atslab__0, statmp26) ;
ATSINSstore_con1_ofs(statmp25, postiats_tysum_8, atslab__1, statmp29) ;
ATSINSstore_con1_ofs(statmp25, postiats_tysum_8, atslab__2, statmp31) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1050(line=45, offs=1) -- 1381(line=60, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp24, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp24, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp24, postiats_tysum_4, atslab__0, ATSPMVstring("n")) ;
ATSINSstore_con1_ofs(statmp24, postiats_tysum_4, atslab__1, statmp25) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1036(line=44, offs=1) -- 1383(line=61, offs=2)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp23, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp23, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp23, postiats_tysum_4, atslab__0, ATSPMVstring("tup")) ;
ATSINSstore_con1_ofs(statmp23, postiats_tysum_4, atslab__1, statmp24) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1558(line=72, offs=26) -- 1567(line=72, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp55, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp55, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp55, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1541(line=72, offs=9) -- 1568(line=72, offs=36)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp54, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp54, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp54, postiats_tysum_7, atslab__0, ATSPMVstring(">")) ;
ATSINSstore_con1_ofs(statmp54, postiats_tysum_7, atslab__1, statmp20) ;
ATSINSstore_con1_ofs(statmp54, postiats_tysum_7, atslab__2, statmp55) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1595(line=73, offs=26) -- 1604(line=73, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp58, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp58, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp58, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1579(line=73, offs=10) -- 1605(line=73, offs=36)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp57, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp57, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp57, postiats_tysum_7, atslab__0, ATSPMVstring(">=")) ;
ATSINSstore_con1_ofs(statmp57, postiats_tysum_7, atslab__1, statmp21) ;
ATSINSstore_con1_ofs(statmp57, postiats_tysum_7, atslab__2, statmp58) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1632(line=75, offs=11) -- 1648(line=75, offs=27)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp61, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp61, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp61, postiats_tysum_5, atslab__0, statmp22) ;
ATSINSstore_con1_ofs(statmp61, postiats_tysum_5, atslab__1, statmp20) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1664(line=75, offs=43) -- 1673(line=75, offs=52)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp63, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp63, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp63, postiats_tysum_6, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1649(line=75, offs=28) -- 1674(line=75, offs=53)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp62, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp62, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp62, postiats_tysum_7, atslab__0, ATSPMVstring("-")) ;
ATSINSstore_con1_ofs(statmp62, postiats_tysum_7, atslab__1, statmp21) ;
ATSINSstore_con1_ofs(statmp62, postiats_tysum_7, atslab__2, statmp63) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1625(line=75, offs=4) -- 1675(line=75, offs=54)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp60, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp60, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp60, postiats_tysum_5, atslab__0, statmp61) ;
ATSINSstore_con1_ofs(statmp60, postiats_tysum_5, atslab__1, statmp62) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1723(line=76, offs=47) -- 1745(line=76, offs=69)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp68, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp68, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp68, postiats_tysum_5, atslab__0, statmp23) ;
ATSINSstore_con1_ofs(statmp68, postiats_tysum_5, atslab__1, statmp19) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1716(line=76, offs=40) -- 1749(line=76, offs=73)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp67, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp67, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp67, postiats_tysum_5, atslab__0, statmp68) ;
ATSINSstore_con1_ofs(statmp67, postiats_tysum_5, atslab__1, statmp21) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1699(line=76, offs=23) -- 1750(line=76, offs=74)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp66, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp66, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp66, postiats_tysum_7, atslab__0, ATSPMVstring("-")) ;
ATSINSstore_con1_ofs(statmp66, postiats_tysum_7, atslab__1, statmp20) ;
ATSINSstore_con1_ofs(statmp66, postiats_tysum_7, atslab__2, statmp67) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1687(line=76, offs=11) -- 1751(line=76, offs=75)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp65, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp65, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp65, postiats_tysum_5, atslab__0, statmp22) ;
ATSINSstore_con1_ofs(statmp65, postiats_tysum_5, atslab__1, statmp66) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1680(line=76, offs=4) -- 1755(line=76, offs=79)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp64, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp64, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp64, postiats_tysum_5, atslab__0, statmp65) ;
ATSINSstore_con1_ofs(statmp64, postiats_tysum_5, atslab__1, statmp21) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1609(line=74, offs=3) -- 1763(line=77, offs=8)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp59, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp59, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp59, postiats_tysum_7, atslab__0, ATSPMVstring("+")) ;
ATSINSstore_con1_ofs(statmp59, postiats_tysum_7, atslab__1, statmp60) ;
ATSINSstore_con1_ofs(statmp59, postiats_tysum_7, atslab__2, statmp64) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1769(line=79, offs=3) -- 1778(line=79, offs=12)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp69, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp69, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp69, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1571(line=73, offs=2) -- 1781(line=80, offs=3)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp56, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp56, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp56, postiats_tysum_8, atslab__0, statmp57) ;
ATSINSstore_con1_ofs(statmp56, postiats_tysum_8, atslab__1, statmp59) ;
ATSINSstore_con1_ofs(statmp56, postiats_tysum_8, atslab__2, statmp69) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1811(line=81, offs=28) -- 1820(line=81, offs=37)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp72, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp72, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp72, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1794(line=81, offs=11) -- 1821(line=81, offs=38)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp71, postiats_tysum_7) ;
// #if(1)
ATSINSstore_con1_tag(statmp71, 8) ;
// #endif
ATSINSstore_con1_ofs(statmp71, postiats_tysum_7, atslab__0, ATSPMVstring("<")) ;
ATSINSstore_con1_ofs(statmp71, postiats_tysum_7, atslab__1, statmp20) ;
ATSINSstore_con1_ofs(statmp71, postiats_tysum_7, atslab__2, statmp72) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1826(line=82, offs=4) -- 1835(line=82, offs=13)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp73, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp73, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp73, postiats_tysum_6, atslab__0, ATSPMVi0nt(0)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1843(line=84, offs=4) -- 1852(line=84, offs=13)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp74, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp74, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp74, postiats_tysum_6, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1786(line=81, offs=3) -- 1857(line=86, offs=4)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp70, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp70, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp70, postiats_tysum_8, atslab__0, statmp71) ;
ATSINSstore_con1_ofs(statmp70, postiats_tysum_8, atslab__1, statmp73) ;
ATSINSstore_con1_ofs(statmp70, postiats_tysum_8, atslab__2, statmp74) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1533(line=72, offs=1) -- 1859(line=87, offs=2)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp53, postiats_tysum_8) ;
// #if(1)
ATSINSstore_con1_tag(statmp53, 10) ;
// #endif
ATSINSstore_con1_ofs(statmp53, postiats_tysum_8, atslab__0, statmp54) ;
ATSINSstore_con1_ofs(statmp53, postiats_tysum_8, atslab__1, statmp56) ;
ATSINSstore_con1_ofs(statmp53, postiats_tysum_8, atslab__2, statmp70) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1521(line=71, offs=1) -- 1861(line=88, offs=2)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp52, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp52, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp52, postiats_tysum_4, atslab__0, ATSPMVstring("n")) ;
ATSINSstore_con1_ofs(statmp52, postiats_tysum_4, atslab__1, statmp53) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1507(line=70, offs=1) -- 1863(line=89, offs=2)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp51, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp51, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp51, postiats_tysum_4, atslab__0, ATSPMVstring("sum")) ;
ATSINSstore_con1_ofs(statmp51, postiats_tysum_4, atslab__1, statmp52) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1492(line=69, offs=1) -- 1865(line=90, offs=2)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp50, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp50, 9) ;
// #endif
ATSINSstore_con1_ofs(statmp50, postiats_tysum_4, atslab__0, ATSPMVstring("aux")) ;
ATSINSstore_con1_ofs(statmp50, postiats_tysum_4, atslab__1, statmp51) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1919(line=92, offs=53) -- 1932(line=92, offs=66)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp78, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(statmp78, 2) ;
// #endif
ATSINSstore_con1_ofs(statmp78, postiats_tysum_0, atslab__0, ATSPMVstring("sum")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1903(line=92, offs=37) -- 1933(line=92, offs=67)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp77, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp77, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp77, postiats_tysum_5, atslab__0, statmp50) ;
ATSINSstore_con1_ofs(statmp77, postiats_tysum_5, atslab__1, statmp78) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1934(line=92, offs=68) -- 1943(line=92, offs=77)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp79, postiats_tysum_6) ;
// #if(1)
ATSINSstore_con1_tag(statmp79, 0) ;
// #endif
ATSINSstore_con1_ofs(statmp79, postiats_tysum_6, atslab__0, ATSPMVi0nt(3)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1896(line=92, offs=30) -- 1944(line=92, offs=78)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp76, postiats_tysum_5) ;
// #if(1)
ATSINSstore_con1_tag(statmp76, 4) ;
// #endif
ATSINSstore_con1_ofs(statmp76, postiats_tysum_5, atslab__0, statmp77) ;
ATSINSstore_con1_ofs(statmp76, postiats_tysum_5, atslab__1, statmp79) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/assign02_sol.dats: 1883(line=92, offs=17) -- 1945(line=92, offs=79)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(statmp75, postiats_tysum_4) ;
// #if(1)
ATSINSstore_con1_tag(statmp75, 3) ;
// #endif
ATSINSstore_con1_ofs(statmp75, postiats_tysum_4, atslab__0, ATSPMVstring("sum")) ;
ATSINSstore_con1_ofs(statmp75, postiats_tysum_4, atslab__1, statmp76) ;
ATSINSmove_con1_end()
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_assign02_sol_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
