/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2020-10-6:  2h:20m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
atstkind_t0ype(atstype_int) atslab__2 ;
atstkind_t0ype(atstype_int) atslab__3 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g1int_neg_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_gte_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_get, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_g0int_lt_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatmpdec(statmp0, postiats_tyrec_0) ;
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__4(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_change(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
aux_10(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__19__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 209(line=12, offs=20) -- 372(line=19, offs=2)
*/
/*
local: 
global: fcoin_get$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 200(line=12, offs=11) -- 372(line=19, offs=2)
*/
ATSINSflab(__patsflab_fcoin_get):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 221(line=14, offs=6) -- 226(line=14, offs=11)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__eq_g0int_int__1__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 218(line=14, offs=3) -- 348(line=18, offs=10)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 232(line=14, offs=17) -- 242(line=14, offs=27)
*/
ATSINSmove(tmpret1, ATSSELfltrec(statmp0, postiats_tyrec_0, atslab__0)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 253(line=15, offs=11) -- 258(line=15, offs=16)
*/
ATSINSmove(tmp7, ATSLIB_056_prelude__eq_g0int_int__1__2(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 250(line=15, offs=8) -- 348(line=18, offs=10)
*/
ATSif(
tmp7
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 264(line=15, offs=22) -- 274(line=15, offs=32)
*/
ATSINSmove(tmpret1, ATSSELfltrec(statmp0, postiats_tyrec_0, atslab__1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 285(line=16, offs=11) -- 290(line=16, offs=16)
*/
ATSINSmove(tmp10, ATSLIB_056_prelude__eq_g0int_int__1__3(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 282(line=16, offs=8) -- 348(line=18, offs=10)
*/
ATSif(
tmp10
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 296(line=16, offs=22) -- 306(line=16, offs=32)
*/
ATSINSmove(tmpret1, ATSSELfltrec(statmp0, postiats_tyrec_0, atslab__2)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 317(line=17, offs=11) -- 322(line=17, offs=16)
*/
ATSINSmove(tmp13, ATSLIB_056_prelude__eq_g0int_int__1__4(arg0, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 314(line=17, offs=8) -- 348(line=18, offs=10)
*/
ATSif(
tmp13
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 328(line=17, offs=22) -- 338(line=17, offs=32)
*/
ATSINSmove(tmpret1, ATSSELfltrec(statmp0, postiats_tyrec_0, atslab__3)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 346(line=18, offs=8) -- 348(line=18, offs=10)
*/
ATSINSmove(tmpret1, atspre_g1int_neg_int(ATSPMVi0nt(1))) ;

} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_get] */

#if(0)
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp4)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3__1, atspre_g0int_eq_int(arg0, tmp4__1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__1] */

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3__2, atspre_g0int_eq_int(arg0, tmp4__2)) ;

ATSfunbody_end()
ATSreturn(tmpret3__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__2] */

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3__3, atspre_g0int_eq_int(arg0, tmp4__3)) ;

ATSfunbody_end()
ATSreturn(tmpret3__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__3] */

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$4(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__4(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__4, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4__4, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3__4, atspre_g0int_eq_int(arg0, tmp4__4)) ;

ATSfunbody_end()
ATSreturn(tmpret3__4) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__4] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 422(line=21, offs=23) -- 637(line=30, offs=4)
*/
/*
local: 
global: fcoin_change$9$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_change(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 410(line=21, offs=11) -- 637(line=30, offs=4)
*/
ATSINSflab(__patsflab_fcoin_change):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 430(line=22, offs=1) -- 637(line=30, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 621(line=29, offs=3) -- 633(line=29, offs=15)
*/
ATSINSmove(tmpret16, aux_10(arg0, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 430(line=22, offs=1) -- 637(line=30, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_change] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 440(line=23, offs=7) -- 597(line=26, offs=36)
*/
/*
local: aux_10$0(level=1)
global: aux_10$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
aux_10(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 440(line=23, offs=7) -- 597(line=26, offs=36)
*/
ATSINSflab(__patsflab_aux_10):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 477(line=24, offs=8) -- 484(line=24, offs=15)
*/
ATSINSmove(tmp18, ATSLIB_056_prelude__gt_g0int_int__11__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 474(line=24, offs=5) -- 597(line=26, offs=36)
*/
ATSif(
tmp18
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 499(line=25, offs=10) -- 505(line=25, offs=16)
*/
ATSINSmove(tmp23, ATSLIB_056_prelude__gte_g0int_int__14__1(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 496(line=25, offs=7) -- 560(line=25, offs=71)
*/
ATSif(
tmp23
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 521(line=25, offs=32) -- 524(line=25, offs=35)
*/
ATSINSmove(tmp29, atspre_g0int_sub_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 511(line=25, offs=22) -- 525(line=25, offs=36)
*/
ATSINSmove(tmp28, aux_10(arg0, tmp29)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 537(line=25, offs=48) -- 548(line=25, offs=59)
*/
ATSINSmove(tmp32, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__fcoin_get(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 533(line=25, offs=44) -- 548(line=25, offs=59)
*/
ATSINSmove(tmp31, atspre_g0int_sub_int(arg0, tmp32)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 528(line=25, offs=39) -- 553(line=25, offs=64)
*/
ATSINSmove(tmp30, aux_10(tmp31, arg1)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 511(line=25, offs=22) -- 553(line=25, offs=64)
*/
ATSINSmove(tmpret17, atspre_g0int_add_int(tmp28, tmp30)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 559(line=25, offs=70) -- 560(line=25, offs=71)
*/
ATSINSmove(tmpret17, ATSPMVi0nt(0)) ;
} /* ATSendif */
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 575(line=26, offs=14) -- 582(line=26, offs=21)
*/
ATSINSmove(tmp33, ATSLIB_056_prelude__lt_g0int_int__19__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 572(line=26, offs=11) -- 596(line=26, offs=35)
*/
ATSif(
tmp33
) ATSthen() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 588(line=26, offs=27) -- 589(line=26, offs=28)
*/
ATSINSmove(tmpret17, ATSPMVi0nt(0)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 595(line=26, offs=34) -- 596(line=26, offs=35)
*/
ATSINSmove(tmpret17, ATSPMVi0nt(1)) ;
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [aux_10] */

#if(0)
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12100(line=626, offs=3) -- 12139(line=626, offs=42)
*/
/*
local: 
global: gt_g0int_int$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4632)
tmparg = S2Evar(tk(4632))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12085(line=625, offs=1) -- 12139(line=626, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12126(line=626, offs=29) -- 12137(line=626, offs=40)
*/
ATSINSmove(tmp20, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4632))>)(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12109(line=626, offs=12) -- 12139(line=626, offs=42)
*/
ATSINSmove(tmpret19, PMVtmpltcst(g0int_gt<S2Evar(tk(4632))>)(arg0, tmp20)) ;

ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__11] */
#endif // end of [TEMPLATE]

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12100(line=626, offs=3) -- 12139(line=626, offs=42)
*/
/*
local: 
global: gt_g0int_int$11$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4632)
tmparg = S2Evar(tk(4632))
tmpsub = Some(tk(4632) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12085(line=625, offs=1) -- 12139(line=626, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12126(line=626, offs=29) -- 12137(line=626, offs=40)
*/
ATSINSmove(tmp20__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12109(line=626, offs=12) -- 12139(line=626, offs=42)
*/
ATSINSmove(tmpret19__1, atspre_g0int_gt_int(arg0, tmp20__1)) ;

ATSfunbody_end()
ATSreturn(tmpret19__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__11__1] */

#if(0)
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12178(line=630, offs=3) -- 12218(line=630, offs=43)
*/
/*
local: 
global: gte_g0int_int$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4633)
tmparg = S2Evar(tk(4633))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12162(line=629, offs=1) -- 12218(line=630, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12205(line=630, offs=30) -- 12216(line=630, offs=41)
*/
ATSINSmove(tmp25, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4633))>)(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12187(line=630, offs=12) -- 12218(line=630, offs=43)
*/
ATSINSmove(tmpret24, PMVtmpltcst(g0int_gte<S2Evar(tk(4633))>)(arg0, tmp25)) ;

ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__14] */
#endif // end of [TEMPLATE]

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 12178(line=630, offs=3) -- 12218(line=630, offs=43)
*/
/*
local: 
global: gte_g0int_int$14$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4633)
tmparg = S2Evar(tk(4633))
tmpsub = Some(tk(4633) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12162(line=629, offs=1) -- 12218(line=630, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12205(line=630, offs=30) -- 12216(line=630, offs=41)
*/
ATSINSmove(tmp25__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12187(line=630, offs=12) -- 12218(line=630, offs=43)
*/
ATSINSmove(tmpret24__1, atspre_g0int_gte_int(arg0, tmp25__1)) ;

ATSfunbody_end()
ATSreturn(tmpret24__1) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__14__1] */

#if(0)
/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp35, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4630))>)(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret34, PMVtmpltcst(g0int_lt<S2Evar(tk(4630))>)(arg0, tmp35)) ;

ATSfunbody_end()
ATSreturn(tmpret34) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__19] */
#endif // end of [TEMPLATE]

/*
/home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$19$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = Some(tk(4630) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__19__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp35__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Apps/ATS2-Postiats-0.4.1/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret34__1, atspre_g0int_lt_int(arg0, tmp35__1)) ;

ATSfunbody_end()
ATSreturn(tmpret34__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__19__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_fcoin_change_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/fcoin_change.dats: 92(line=5, offs=16) -- 106(line=5, offs=30)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(statmp0, postiats_tyrec_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs(statmp0, postiats_tyrec_0, atslab__1, ATSPMVi0nt(5)) ;
ATSINSstore_fltrec_ofs(statmp0, postiats_tyrec_0, atslab__2, ATSPMVi0nt(10)) ;
ATSINSstore_fltrec_ofs(statmp0, postiats_tyrec_0, atslab__3, ATSPMVi0nt(25)) ;
ATSINSmove_fltrec_end()
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
