/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2020-10-6:  2h:20m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_3 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_4 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_bool) atslab__0 ;
} postiats_tysum_5 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
atstype_boxed atslab__2 ;
} postiats_tysum_6 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
atstype_boxed atslab__2 ;
} postiats_tysum_7 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
} postiats_tysum_8 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tysum_9 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm, (atstkind_type(atstype_ptrk), atstype_boxed), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_FILE_stdout)
ATSdyncst_mac(atspre_fprint_int)
ATSdyncst_mac(atspre_fprint_bool)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atsvoid_t0ype
print_myl_1__1(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0__1(atstkind_type(atstype_ptrk), atstype_boxed) ;

ATSstatic()
atsvoid_t0ype
print_myl_1__1__1(atstkind_type(atstype_ptrk), atstype_boxed) ;

#if(0)
/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 157(line=7, offs=31) -- 409(line=22, offs=2)
*/
/*
local: 
global: fprint_mylist$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Ecst(t0erm)
tmpsub = None()
*/
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 137(line=7, offs=11) -- 409(line=22, offs=2)
*/
ATSINSflab(__patsflab_fprint_mylist):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 177(line=9, offs=1) -- 407(line=21, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 369(line=19, offs=3) -- 385(line=19, offs=19)
*/
ATSINSmove_void(tmp6, atspre_fprint_string(arg0, ATSPMVstring("["))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 389(line=20, offs=3) -- 401(line=20, offs=15)
*/
ATSINSmove_void(tmpret0, ATSfunclo_fun(PMVd2vfunlab(d2v=print_myl$76(1), flab=print_myl_1$0(level=1)), (atstype_boxed), atsvoid_t0ype)(arg1)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 177(line=9, offs=1) -- 407(line=21, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 187(line=10, offs=7) -- 363(line=17, offs=6)
*/
/*
local: print_myl_1$0(level=1)
global: print_myl_1$0(level=1)
local: out$74(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: out$74(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
atsvoid_t0ype
print_myl_1__1(atstkind_type(atstype_ptrk) env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
// ATStmpdec_void(tmpret1) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstype_boxed) ;
// ATStmpdec_void(tmp4) ;
// ATStmpdec_void(tmp5) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 187(line=10, offs=7) -- 363(line=17, offs=6)
*/
ATSINSflab(__patsflab_print_myl_1):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 227(line=11, offs=5) -- 363(line=17, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 244(line=12, offs=7) -- 256(line=12, offs=19)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 197(line=10, offs=17) -- 199(line=10, offs=19)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 256(line=12, offs=19) -- 256(line=12, offs=19)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 260(line=12, offs=23) -- 276(line=12, offs=39)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(env0, ATSPMVstring("]"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 283(line=13, offs=7) -- 301(line=13, offs=25)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 197(line=10, offs=17) -- 199(line=10, offs=19)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINScaseof_fail("/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 227(line=11, offs=5) -- 363(line=17, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 301(line=13, offs=25) -- 301(line=13, offs=25)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 295(line=13, offs=19) -- 297(line=13, offs=21)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 298(line=13, offs=22) -- 300(line=13, offs=24)
*/
ATSINSmove(tmp3, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 316(line=15, offs=5) -- 337(line=15, offs=26)
*/
ATSINSmove_void(tmp4, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(env0, tmp2)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 316(line=15, offs=5) -- 337(line=15, offs=26)
*/
ATSINSmove_void(tmp5, atspre_fprint_string(env0, ATSPMVstring(" ,"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 343(line=16, offs=5) -- 355(line=16, offs=17)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_print_myl_1) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [print_myl_1__1] */
#endif // end of [TEMPLATE]

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 468(line=29, offs=12) -- 503(line=30, offs=29)
*/
/*
local: 
global: print_t0erm$2$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret7) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 457(line=29, offs=1) -- 503(line=30, offs=29)
*/
ATSINSflab(__patsflab_print_t0erm):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 475(line=30, offs=1) -- 503(line=30, offs=29)
*/
ATSINSmove_void(tmpret7, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atspre_FILE_stdout, arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret7) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__print_t0erm] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 546(line=33, offs=13) -- 1533(line=83, offs=2)
*/
/*
local: 
global: fprint_t0erm$3$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstype_boxed) ;
ATStmpdec(tmp13, atstype_boxed) ;
ATStmpdec(tmp14, atstype_boxed) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17, atstype_boxed) ;
ATStmpdec(tmp18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp19, atstype_boxed) ;
ATStmpdec(tmp20, atstype_boxed) ;
ATStmpdec(tmp21, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp22, atstype_boxed) ;
ATStmpdec(tmp23, atstype_boxed) ;
ATStmpdec(tmp24, atstype_boxed) ;
ATStmpdec(tmp25, atstype_boxed) ;
ATStmpdec(tmp26, atstype_boxed) ;
ATStmpdec(tmp27, atstype_boxed) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp29) ;
// ATStmpdec_void(tmp30) ;
// ATStmpdec_void(tmp31) ;
// ATStmpdec_void(tmp32) ;
// ATStmpdec_void(tmp33) ;
// ATStmpdec_void(tmp34) ;
// ATStmpdec_void(tmp35) ;
// ATStmpdec_void(tmp36) ;
// ATStmpdec_void(tmp37) ;
// ATStmpdec_void(tmp38) ;
// ATStmpdec_void(tmp39) ;
// ATStmpdec_void(tmp40) ;
// ATStmpdec_void(tmp41) ;
// ATStmpdec_void(tmp42) ;
// ATStmpdec_void(tmp43) ;
// ATStmpdec_void(tmp44) ;
// ATStmpdec_void(tmp45) ;
// ATStmpdec_void(tmp46) ;
// ATStmpdec_void(tmp47) ;
// ATStmpdec_void(tmp48) ;
// ATStmpdec_void(tmp49) ;
// ATStmpdec_void(tmp50) ;
// ATStmpdec_void(tmp51) ;
// ATStmpdec_void(tmp52) ;
// ATStmpdec_void(tmp53) ;
// ATStmpdec_void(tmp54) ;
// ATStmpdec_void(tmp55) ;
// ATStmpdec_void(tmp56) ;
// ATStmpdec_void(tmp57) ;
// ATStmpdec_void(tmp58) ;
// ATStmpdec_void(tmp59) ;
// ATStmpdec_void(tmp60) ;
// ATStmpdec_void(tmp61) ;
// ATStmpdec_void(tmp62) ;
// ATStmpdec_void(tmp63) ;
// ATStmpdec_void(tmp64) ;
// ATStmpdec_void(tmp72) ;
// ATStmpdec_void(tmp73) ;
// ATStmpdec_void(tmp74) ;
// ATStmpdec_void(tmp75) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 534(line=33, offs=1) -- 1533(line=83, offs=2)
*/
ATSINSflab(__patsflab_fprint_t0erm):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 560(line=35, offs=1) -- 1455(line=80, offs=32)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 574(line=36, offs=3) -- 583(line=36, offs=12)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 0)) { ATSINSgoto(__atstmplab6) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 583(line=36, offs=12) -- 583(line=36, offs=12)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 581(line=36, offs=10) -- 583(line=36, offs=12)
*/
ATSINSmove(tmp9, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 590(line=37, offs=3) -- 622(line=37, offs=35)
*/
ATSINSmove_void(tmp29, atspre_fprint_string(arg0, ATSPMVstring("T0Mint("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 590(line=37, offs=3) -- 622(line=37, offs=35)
*/
ATSINSmove_void(tmp30, atspre_fprint_int(arg0, tmp9)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 590(line=37, offs=3) -- 622(line=37, offs=35)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 625(line=38, offs=3) -- 634(line=38, offs=12)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 2)) { ATSINSgoto(__atstmplab8) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 634(line=38, offs=12) -- 634(line=38, offs=12)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 632(line=38, offs=10) -- 634(line=38, offs=12)
*/
ATSINSmove(tmp10, ATSSELcon(arg1, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 641(line=39, offs=3) -- 673(line=39, offs=35)
*/
ATSINSmove_void(tmp31, atspre_fprint_string(arg0, ATSPMVstring("T0Mvar("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 641(line=39, offs=3) -- 673(line=39, offs=35)
*/
ATSINSmove_void(tmp32, atspre_fprint_string(arg0, tmp10)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 641(line=39, offs=3) -- 673(line=39, offs=35)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 676(line=40, offs=3) -- 690(line=40, offs=17)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 3)) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 690(line=40, offs=17) -- 690(line=40, offs=17)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 683(line=40, offs=10) -- 685(line=40, offs=12)
*/
ATSINSmove(tmp11, ATSSELcon(arg1, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 687(line=40, offs=14) -- 689(line=40, offs=16)
*/
ATSINSmove(tmp12, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 696(line=41, offs=3) -- 741(line=42, offs=38)
*/
ATSINSmove_void(tmp33, atspre_fprint_string(arg0, ATSPMVstring("T0Mlam("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 696(line=41, offs=3) -- 741(line=42, offs=38)
*/
ATSINSmove_void(tmp34, atspre_fprint_string(arg0, tmp11)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 696(line=41, offs=3) -- 741(line=42, offs=38)
*/
ATSINSmove_void(tmp35, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 696(line=41, offs=3) -- 741(line=42, offs=38)
*/
ATSINSmove_void(tmp36, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp12)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 696(line=41, offs=3) -- 741(line=42, offs=38)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 744(line=43, offs=3) -- 758(line=43, offs=17)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 4)) { ATSINSgoto(__atstmplab12) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 758(line=43, offs=17) -- 758(line=43, offs=17)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 751(line=43, offs=10) -- 753(line=43, offs=12)
*/
ATSINSmove(tmp13, ATSSELcon(arg1, postiats_tysum_4, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 755(line=43, offs=14) -- 757(line=43, offs=16)
*/
ATSINSmove(tmp14, ATSSELcon(arg1, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 764(line=44, offs=3) -- 809(line=45, offs=38)
*/
ATSINSmove_void(tmp37, atspre_fprint_string(arg0, ATSPMVstring("T0Mapp("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 764(line=44, offs=3) -- 809(line=45, offs=38)
*/
ATSINSmove_void(tmp38, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp13)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 764(line=44, offs=3) -- 809(line=45, offs=38)
*/
ATSINSmove_void(tmp39, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 764(line=44, offs=3) -- 809(line=45, offs=38)
*/
ATSINSmove_void(tmp40, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp14)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 764(line=44, offs=3) -- 809(line=45, offs=38)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 815(line=47, offs=3) -- 826(line=47, offs=14)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 1)) { ATSINSgoto(__atstmplab14) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 826(line=47, offs=14) -- 826(line=47, offs=14)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 823(line=47, offs=11) -- 826(line=47, offs=14)
*/
ATSINSmove(tmp15, ATSSELcon(arg1, postiats_tysum_5, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 833(line=48, offs=3) -- 874(line=50, offs=26)
*/
ATSINSmove_void(tmp41, atspre_fprint_string(arg0, ATSPMVstring("T0Mbool("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 833(line=48, offs=3) -- 874(line=50, offs=26)
*/
ATSINSmove_void(tmp42, atspre_fprint_bool(arg0, tmp15)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 833(line=48, offs=3) -- 874(line=50, offs=26)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 877(line=51, offs=3) -- 892(line=51, offs=18)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 7)) { ATSINSgoto(__atstmplab16) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 892(line=51, offs=18) -- 892(line=51, offs=18)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 885(line=51, offs=11) -- 887(line=51, offs=13)
*/
ATSINSmove(tmp16, ATSSELcon(arg1, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 889(line=51, offs=15) -- 891(line=51, offs=17)
*/
ATSINSmove(tmp17, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 898(line=52, offs=3) -- 948(line=54, offs=35)
*/
ATSINSmove_void(tmp43, atspre_fprint_string(arg0, ATSPMVstring("T0Mopr1("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 898(line=52, offs=3) -- 948(line=54, offs=35)
*/
ATSINSmove_void(tmp44, atspre_fprint_string(arg0, tmp16)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 898(line=52, offs=3) -- 948(line=54, offs=35)
*/
ATSINSmove_void(tmp45, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 898(line=52, offs=3) -- 948(line=54, offs=35)
*/
ATSINSmove_void(tmp46, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp17)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 898(line=52, offs=3) -- 948(line=54, offs=35)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 951(line=55, offs=3) -- 970(line=55, offs=22)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 8)) { ATSINSgoto(__atstmplab18) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 970(line=55, offs=22) -- 970(line=55, offs=22)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 959(line=55, offs=11) -- 961(line=55, offs=13)
*/
ATSINSmove(tmp18, ATSSELcon(arg1, postiats_tysum_6, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 963(line=55, offs=15) -- 965(line=55, offs=17)
*/
ATSINSmove(tmp19, ATSSELcon(arg1, postiats_tysum_6, atslab__1)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 967(line=55, offs=19) -- 969(line=55, offs=21)
*/
ATSINSmove(tmp20, ATSSELcon(arg1, postiats_tysum_6, atslab__2)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp47, atspre_fprint_string(arg0, ATSPMVstring("T0Mopr2("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp48, atspre_fprint_string(arg0, tmp18)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp49, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp50, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp19)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp51, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmp52, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp20)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 976(line=56, offs=3) -- 1036(line=58, offs=45)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1101(line=64, offs=3) -- 1116(line=64, offs=18)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 9)) { ATSINSgoto(__atstmplab20) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1116(line=64, offs=18) -- 1116(line=64, offs=18)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1109(line=64, offs=11) -- 1111(line=64, offs=13)
*/
ATSINSmove(tmp21, ATSSELcon(arg1, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1113(line=64, offs=15) -- 1115(line=64, offs=17)
*/
ATSINSmove(tmp22, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1122(line=65, offs=3) -- 1165(line=65, offs=46)
*/
ATSINSmove_void(tmp53, atspre_fprint_string(arg0, ATSPMVstring("T0Mfix1("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1122(line=65, offs=3) -- 1165(line=65, offs=46)
*/
ATSINSmove_void(tmp54, atspre_fprint_string(arg0, tmp21)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1122(line=65, offs=3) -- 1165(line=65, offs=46)
*/
ATSINSmove_void(tmp55, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1122(line=65, offs=3) -- 1165(line=65, offs=46)
*/
ATSINSmove_void(tmp56, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp22)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1122(line=65, offs=3) -- 1165(line=65, offs=46)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1171(line=67, offs=3) -- 1190(line=67, offs=22)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 10)) { ATSINSgoto(__atstmplab22) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1190(line=67, offs=22) -- 1190(line=67, offs=22)
*/
ATSINSlab(__atstmplab21):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1179(line=67, offs=11) -- 1181(line=67, offs=13)
*/
ATSINSmove(tmp23, ATSSELcon(arg1, postiats_tysum_7, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1183(line=67, offs=15) -- 1185(line=67, offs=17)
*/
ATSINSmove(tmp24, ATSSELcon(arg1, postiats_tysum_7, atslab__1)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1187(line=67, offs=19) -- 1189(line=67, offs=21)
*/
ATSINSmove(tmp25, ATSSELcon(arg1, postiats_tysum_7, atslab__2)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp57, atspre_fprint_string(arg0, ATSPMVstring("T0Mcond("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp58, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp23)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp59, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp60, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp24)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp61, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmp62, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp25)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1196(line=68, offs=3) -- 1256(line=70, offs=45)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1332(line=72, offs=3) -- 1342(line=72, offs=13)
*/
ATSINSlab(__atstmplab22):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 5)) { ATSINSgoto(__atstmplab24) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1342(line=72, offs=13) -- 1342(line=72, offs=13)
*/
ATSINSlab(__atstmplab23):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1339(line=72, offs=10) -- 1342(line=72, offs=13)
*/
ATSINSmove(tmp26, ATSSELcon(arg1, postiats_tysum_8, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1347(line=73, offs=1) -- 1387(line=75, offs=25)
*/
ATSINSmove_void(tmp63, atspre_fprint_string(arg0, ATSPMVstring("T0Mtup("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1347(line=73, offs=1) -- 1387(line=75, offs=25)
*/
ATSINSmove_void(tmp64, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0__1(arg0, tmp26)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1347(line=73, offs=1) -- 1387(line=75, offs=25)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1391(line=77, offs=3) -- 1402(line=77, offs=14)
*/
ATSINSlab(__atstmplab24):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 552(line=33, offs=19) -- 554(line=33, offs=21)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg1, 6)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1402(line=77, offs=14) -- 1402(line=77, offs=14)
*/
ATSINSlab(__atstmplab25):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1398(line=77, offs=10) -- 1399(line=77, offs=11)
*/
ATSINSmove(tmp27, ATSSELcon(arg1, postiats_tysum_9, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1400(line=77, offs=12) -- 1401(line=77, offs=13)
*/
ATSINSmove(tmp28, ATSSELcon(arg1, postiats_tysum_9, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1408(line=78, offs=3) -- 1455(line=80, offs=32)
*/
ATSINSmove_void(tmp72, atspre_fprint_string(arg0, ATSPMVstring("T0Mprj("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1408(line=78, offs=3) -- 1455(line=80, offs=32)
*/
ATSINSmove_void(tmp73, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp27)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1408(line=78, offs=3) -- 1455(line=80, offs=32)
*/
ATSINSmove_void(tmp74, atspre_fprint_string(arg0, ATSPMVstring(", "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1408(line=78, offs=3) -- 1455(line=80, offs=32)
*/
ATSINSmove_void(tmp75, atspre_fprint_int(arg0, tmp28)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 1408(line=78, offs=3) -- 1455(line=80, offs=32)
*/
ATSINSmove_void(tmpret8, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 157(line=7, offs=31) -- 409(line=22, offs=2)
*/
/*
local: 
global: fprint_mylist$0$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = S2Ecst(t0erm)
tmpsub = Some()
*/
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0__1(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0__1) ;
// ATStmpdec_void(tmp6__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 137(line=7, offs=11) -- 409(line=22, offs=2)
*/
ATSINSflab(__patsflab_fprint_mylist):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 177(line=9, offs=1) -- 407(line=21, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 369(line=19, offs=3) -- 385(line=19, offs=19)
*/
ATSINSmove_void(tmp6__1, atspre_fprint_string(arg0, ATSPMVstring("["))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 389(line=20, offs=3) -- 401(line=20, offs=15)
*/
ATSINSmove_void(tmpret0__1, print_myl_1__1__1(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 177(line=9, offs=1) -- 407(line=21, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0__1) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_mylib_057_mylib_056_sats__fprint_mylist__0__1] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 187(line=10, offs=7) -- 363(line=17, offs=6)
*/
/*
local: print_myl_1$1(level=2)
global: print_myl_1$1(level=2)
local: out$74(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: out$74(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
atsvoid_t0ype
print_myl_1__1__1(atstkind_type(atstype_ptrk) env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
// ATStmpdec_void(tmpret1__1) ;
ATStmpdec(tmp2__1, atstype_boxed) ;
ATStmpdec(tmp3__1, atstype_boxed) ;
// ATStmpdec_void(tmp4__1) ;
// ATStmpdec_void(tmp5__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 187(line=10, offs=7) -- 363(line=17, offs=6)
*/
ATSINSflab(__patsflab_print_myl_1):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 227(line=11, offs=5) -- 363(line=17, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 244(line=12, offs=7) -- 256(line=12, offs=19)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 197(line=10, offs=17) -- 199(line=10, offs=19)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 256(line=12, offs=19) -- 256(line=12, offs=19)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 260(line=12, offs=23) -- 276(line=12, offs=39)
*/
ATSINSmove_void(tmpret1__1, atspre_fprint_string(env0, ATSPMVstring("]"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 283(line=13, offs=7) -- 301(line=13, offs=25)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 197(line=10, offs=17) -- 199(line=10, offs=19)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINScaseof_fail("/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 227(line=11, offs=5) -- 363(line=17, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 301(line=13, offs=25) -- 301(line=13, offs=25)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 295(line=13, offs=19) -- 297(line=13, offs=21)
*/
ATSINSmove(tmp2__1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 298(line=13, offs=22) -- 300(line=13, offs=24)
*/
ATSINSmove(tmp3__1, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 316(line=15, offs=5) -- 337(line=15, offs=26)
*/
ATSINSmove_void(tmp4__1, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_056_sats__fprint_t0erm(env0, tmp2__1)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 316(line=15, offs=5) -- 337(line=15, offs=26)
*/
ATSINSmove_void(tmp5__1, atspre_fprint_string(env0, ATSPMVstring(" ,"))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign02/MySolution/lambda0_print.dats: 343(line=16, offs=5) -- 355(line=16, offs=17)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp3__1) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_print_myl_1) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret1__1) ;
} /* end of [print_myl_1__1__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign02_057_MySolution_057_lambda0_print_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
