/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2020-9-21: 14h: 8m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstype_boxed atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_3 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
atstype_boxed atslab__2 ;
} postiats_tysum_4 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_bool) atslab__0 ;
} postiats_tysum_5 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm, (atstkind_type(atstype_ptrk), atstype_boxed), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_FILE_stdout)
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_mac(atspre_fprint_int)
ATSdyncst_mac(atspre_fprint_bool)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__print_t0erm(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 147(line=7, offs=12) -- 182(line=8, offs=29)
*/
/*
local: 
global: print_t0erm$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__print_t0erm(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 136(line=7, offs=1) -- 182(line=8, offs=29)
*/
ATSINSflab(__patsflab_print_t0erm):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 154(line=8, offs=1) -- 182(line=8, offs=29)
*/
ATSINSmove_void(tmpret0, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atspre_FILE_stdout, arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__print_t0erm] */

/*
/home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 225(line=11, offs=13) -- 630(line=30, offs=2)
*/
/*
local: 
global: fprint_t0erm$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret1) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstype_boxed) ;
ATStmpdec(tmp7, atstype_boxed) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp9, atstype_boxed) ;
ATStmpdec(tmp10, atstype_boxed) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
// ATStmpdec_void(tmp15) ;
// ATStmpdec_void(tmp16) ;
// ATStmpdec_void(tmp17) ;
// ATStmpdec_void(tmp18) ;
// ATStmpdec_void(tmp19) ;
// ATStmpdec_void(tmp20) ;
// ATStmpdec_void(tmp21) ;
// ATStmpdec_void(tmp22) ;
// ATStmpdec_void(tmp23) ;
// ATStmpdec_void(tmp24) ;
// ATStmpdec_void(tmp25) ;
// ATStmpdec_void(tmp26) ;
// ATStmpdec_void(tmp27) ;
// ATStmpdec_void(tmp28) ;
// ATStmpdec_void(tmp29) ;
// ATStmpdec_void(tmp30) ;
// ATStmpdec_void(tmp31) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 213(line=11, offs=1) -- 630(line=30, offs=2)
*/
ATSINSflab(__patsflab_fprint_t0erm):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 239(line=13, offs=1) -- 628(line=29, offs=36)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 253(line=14, offs=3) -- 262(line=14, offs=12)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 0)) { ATSINSgoto(__atstmplab2) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 262(line=14, offs=12) -- 262(line=14, offs=12)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 260(line=14, offs=10) -- 262(line=14, offs=12)
*/
ATSINSmove(tmp2, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 269(line=15, offs=3) -- 301(line=15, offs=35)
*/
ATSINSmove_void(tmp12, atspre_fprint_string(arg0, ATSPMVstring("T0Mint("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 269(line=15, offs=3) -- 301(line=15, offs=35)
*/
ATSINSmove_void(tmp13, atspre_fprint_int(arg0, tmp2)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 269(line=15, offs=3) -- 301(line=15, offs=35)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 304(line=16, offs=3) -- 313(line=16, offs=12)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 1)) { ATSINSgoto(__atstmplab4) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 313(line=16, offs=12) -- 313(line=16, offs=12)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 311(line=16, offs=10) -- 313(line=16, offs=12)
*/
ATSINSmove(tmp3, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 320(line=17, offs=3) -- 352(line=17, offs=35)
*/
ATSINSmove_void(tmp14, atspre_fprint_string(arg0, ATSPMVstring("T0Mvar("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 320(line=17, offs=3) -- 352(line=17, offs=35)
*/
ATSINSmove_void(tmp15, atspre_fprint_string(arg0, tmp3)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 320(line=17, offs=3) -- 352(line=17, offs=35)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 355(line=18, offs=3) -- 369(line=18, offs=17)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 2)) { ATSINSgoto(__atstmplab6) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 369(line=18, offs=17) -- 369(line=18, offs=17)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 362(line=18, offs=10) -- 364(line=18, offs=12)
*/
ATSINSmove(tmp4, ATSSELcon(arg1, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 366(line=18, offs=14) -- 368(line=18, offs=16)
*/
ATSINSmove(tmp5, ATSSELcon(arg1, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 375(line=19, offs=3) -- 420(line=20, offs=38)
*/
ATSINSmove_void(tmp16, atspre_fprint_string(arg0, ATSPMVstring("T0Mlam("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 375(line=19, offs=3) -- 420(line=20, offs=38)
*/
ATSINSmove_void(tmp17, atspre_fprint_string(arg0, tmp4)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 375(line=19, offs=3) -- 420(line=20, offs=38)
*/
ATSINSmove_void(tmp18, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 375(line=19, offs=3) -- 420(line=20, offs=38)
*/
ATSINSmove_void(tmp19, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp5)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 375(line=19, offs=3) -- 420(line=20, offs=38)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 423(line=21, offs=3) -- 437(line=21, offs=17)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 3)) { ATSINSgoto(__atstmplab8) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 437(line=21, offs=17) -- 437(line=21, offs=17)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 430(line=21, offs=10) -- 432(line=21, offs=12)
*/
ATSINSmove(tmp6, ATSSELcon(arg1, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 434(line=21, offs=14) -- 436(line=21, offs=16)
*/
ATSINSmove(tmp7, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 443(line=22, offs=3) -- 488(line=23, offs=38)
*/
ATSINSmove_void(tmp20, atspre_fprint_string(arg0, ATSPMVstring("T0Mapp("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 443(line=22, offs=3) -- 488(line=23, offs=38)
*/
ATSINSmove_void(tmp21, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp6)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 443(line=22, offs=3) -- 488(line=23, offs=38)
*/
ATSINSmove_void(tmp22, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 443(line=22, offs=3) -- 488(line=23, offs=38)
*/
ATSINSmove_void(tmp23, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp7)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 443(line=22, offs=3) -- 488(line=23, offs=38)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 491(line=24, offs=3) -- 510(line=24, offs=22)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg1, 5)) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 510(line=24, offs=22) -- 510(line=24, offs=22)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 499(line=24, offs=11) -- 501(line=24, offs=13)
*/
ATSINSmove(tmp8, ATSSELcon(arg1, postiats_tysum_4, atslab__0)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 503(line=24, offs=15) -- 505(line=24, offs=17)
*/
ATSINSmove(tmp9, ATSSELcon(arg1, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 507(line=24, offs=19) -- 509(line=24, offs=21)
*/
ATSINSmove(tmp10, ATSSELcon(arg1, postiats_tysum_4, atslab__2)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp24, atspre_fprint_string(arg0, ATSPMVstring("T0Mopr2("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp25, atspre_fprint_string(arg0, tmp8)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp26, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp27, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp9)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp28, atspre_fprint_string(arg0, ATSPMVstring("; "))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmp29, _057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm(arg0, tmp10)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 516(line=25, offs=3) -- 576(line=27, offs=45)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 579(line=28, offs=3) -- 588(line=28, offs=12)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 231(line=11, offs=19) -- 233(line=11, offs=21)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg1, 4)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 588(line=28, offs=12) -- 588(line=28, offs=12)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 586(line=28, offs=10) -- 588(line=28, offs=12)
*/
ATSINSmove(tmp11, ATSSELcon(arg1, postiats_tysum_5, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 595(line=29, offs=3) -- 628(line=29, offs=36)
*/
ATSINSmove_void(tmp30, atspre_fprint_string(arg0, ATSPMVstring("T0Mbool("))) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 595(line=29, offs=3) -- 628(line=29, offs=36)
*/
ATSINSmove_void(tmp31, atspre_fprint_bool(arg0, tmp11)) ;

/*
emit_instr: loc0 = /home/amin/Docs/Compiler Design/CS525-2020-Fall/CS525-2020-Fall-a-naghavi/assigns/assign01/MySolution/lambda0_print.dats: 595(line=29, offs=3) -- 628(line=29, offs=36)
*/
ATSINSmove_void(tmpret1, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_056_sats__fprint_t0erm] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_print_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_print_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_print_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_amin_057_Docs_057_Compiler_040_Design_057_CS525_055_2020_055_Fall_057_CS525_055_2020_055_Fall_055_a_055_naghavi_057_assigns_057_assign01_057_MySolution_057_lambda0_print_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
